**T074 Kermeen**

**Prac 3 A**

**Apply feature-scaling techniques like standardization and normalization to numerical features.**

In [1]:
# Rescaling a feature
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
df=pd.read_csv('/content/Sales_with_NaNs_v1.3.csv')
df.head()

Group Customer_Segment  Sales_Before  Sales_After  \
0    Control       High Value    240.548359   300.007568   
1  Treatment       High Value    246.862114   381.337555   
2    Control       High Value    156.978084   179.330464   
3    Control     Medium Value    192.126708   229.278031   
4        NaN       High Value    229.685623          NaN   

   Customer_Satisfaction_Before  Customer_Satisfaction_After Purchase_Made  
0                     74.684767                          NaN            No  
1                    100.000000                   100.000000           Yes  
2                     98.780735                   100.000000            No  
3                     49.333766                    39.811841           Yes  
4                     83.974852                    87.738591           Yes

In [2]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Group'] = le.fit_transform(df['Group'])
df['Customer_Segment'] = le.fit_transform(df['Customer_Segment'])
df['Purchase_Made'] = le.fit_transform(df['Purchase_Made'])
df.tail(3)


Group  Customer_Segment  Sales_Before  Sales_After  \
9997      1                 1    208.107142   322.893351   
9998      1                 2           NaN   431.974901   
9999      0                 1           NaN   124.402398   

      Customer_Satisfaction_Before  Customer_Satisfaction_After  Purchase_Made  
9997                     55.915870                          NaN              0  
9998                     66.082462                     81.27403              0  
9999                     55.692277                     65.28848              1

In [3]:
from sklearn import preprocessing
# create scaler
minmax_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
# scale features
scaled_feature = minmax_scaler.fit_transform(df)
scaled_feature


array([[0.        , 0.        , 0.41434498, ..., 0.67460118,        nan,
        0.        ],
       [0.5       , 0.        , 0.42647353, ..., 1.        , 1.        ,
        0.5       ],
       [0.        , 0.        , 0.25380876, ..., 0.98432772, 1.        ,
        0.        ],
       ...,
       [0.5       , 0.33333333, 0.35202629, ..., 0.43334816,        nan,
        0.        ],
       [0.5       , 0.66666667,        nan, ..., 0.56402825, 0.77100634,
        0.        ],
       [0.        , 0.33333333,        nan, ..., 0.43047412, 0.57552438,
        0.5       ]])

In [4]:
#deleteing missing rows
df = df.dropna()

In [5]:
# Standardizing a Feature
scaler = preprocessing.StandardScaler()
# transform the feature
standardized = scaler.fit_transform(df)
standardized

array([[ 0.40311826, -1.3155852 ,  0.76943012, ...,  1.77738844,
         1.45749585,  0.58603898],
       [-1.02398305, -1.3155852 , -0.84838832, ...,  1.70496791,
         1.45749585, -0.99896303],
       [-1.02398305,  0.54231138, -0.21574988, ..., -1.23202758,
        -1.88000715,  0.58603898],
       ...,
       [ 0.40311826,  1.47125966, -0.73478396, ...,  0.12828581,
         1.00828127, -0.99896303],
       [ 0.40311826,  1.47125966,  1.00042546, ...,  1.09068788,
         1.36980501,  2.17104098],
       [-1.02398305, -1.3155852 , -0.3172356 , ...,  1.31774792,
         1.45749585,  2.17104098]])

In [6]:
print("Mean {}".format(round(standardized.mean())))
print("Standard Deviation: {}".format(standardized.std()))

Mean 0
Standard Deviation: 1.0


In [7]:
# using robust scaler
robust_scaler = preprocessing.RobustScaler()
robust_scaler.fit_transform(df)

array([[ 0.        , -0.5       ,  0.59492088, ...,  1.13936908,
         0.89135733,  0.        ],
       [-1.        , -0.5       , -0.62782024, ...,  1.09407402,
         0.89135733, -1.        ],
       [-1.        ,  0.5       , -0.14967448, ..., -0.74285523,
        -1.1349839 ,  0.        ],
       ...,
       [ 0.        ,  1.        , -0.5419585 , ...,  0.10794603,
         0.61861989, -1.        ],
       [ 0.        ,  1.        ,  0.76950629, ...,  0.70987562,
         0.83811645,  1.        ],
       [-1.        , -0.5       , -0.22637701, ...,  0.8518892 ,
         0.89135733,  1.        ]])

In [8]:
# Normalizing Observations
from sklearn.preprocessing import Normalizer
# create normalizer
normalizer = Normalizer(norm="l2")
# transform feature matrix
normalizer.transform(df)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but Normalizer was fitted without feature names
  warnings.warn(


array([[0.00210184, 0.        , 0.51886385, ..., 0.21018367, 0.21018367,
        0.00210184],
       [0.        , 0.        , 0.56733611, ..., 0.35700447, 0.36141103,
        0.        ],
       [0.        , 0.00654053, 0.62830509, ..., 0.16133445, 0.13019524,
        0.00327026],
       ...,
       [0.00312658, 0.00937975, 0.51053925, ..., 0.22585149, 0.28732965,
        0.        ],
       [0.00197127, 0.00591382, 0.51193163, ..., 0.17433699, 0.19400993,
        0.00394255],
       [0.        , 0.        , 0.58958767, ..., 0.2916873 , 0.31615266,
        0.00632305]])

In [9]:
features_l1_norm = Normalizer(norm="l1").transform(df)
features_l1_norm

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but Normalizer was fitted without feature names
  warnings.warn(


array([[0.00120453, 0.        , 0.2973527 , ..., 0.12045295, 0.12045295,
        0.00120453],
       [0.        , 0.        , 0.29336802, ..., 0.18460608, 0.1868847 ,
        0.        ],
       [0.        , 0.00389446, 0.37411465, ..., 0.09606413, 0.07752276,
        0.00194723],
       ...,
       [0.00172313, 0.00516938, 0.2813688 , ..., 0.12447146, 0.15835335,
        0.        ],
       [0.00115243, 0.00345728, 0.29928024, ..., 0.10191911, 0.1134201 ,
        0.00230485],
       [0.        , 0.        , 0.31238862, ..., 0.15454834, 0.16751112,
        0.00335022]])

In [10]:
# Grouping Observations Using Clustering
from sklearn.cluster import KMeans
# make k-means clusterer
clusterer = KMeans(3, random_state=0)
# fit clusterer
clusterer.fit(df)
# predict groups
df['group'] = clusterer.predict(df)
df.head()

Group  Customer_Segment  Sales_Before  Sales_After  \
1      1                 0    246.862114   381.337555   
2      0                 0    156.978084   179.330464   
3      0                 2    192.126708   229.278031   
5      1                 3    135.573003   218.559988   
6      0                 0    191.713918   222.409356   

   Customer_Satisfaction_Before  Customer_Satisfaction_After  Purchase_Made  \
1                    100.000000                   100.000000              1   
2                     98.780735                   100.000000              0   
3                     49.333766                    39.811841              1   
5                     58.075342                    69.404918              0   
6                     89.967827                    85.120975              1   

   group  
1      1  
2      2  
3      2  
5      2  
6      2

In [11]:
# Deleting Observations with Missing Values
df[~np.isnan(df).any(axis=1)]

Group  Customer_Segment  Sales_Before  Sales_After  \
1         1                 0    246.862114   381.337555   
2         0                 0    156.978084   179.330464   
3         0                 2    192.126708   229.278031   
5         1                 3    135.573003   218.559988   
6         0                 0    191.713918   222.409356   
...     ...               ...           ...          ...   
9989      0                 2    109.386552   145.054224   
9992      1                 2    209.913990   320.791145   
9993      1                 3    163.289805   248.916244   
9995      1                 3    259.695935   415.181694   
9996      0                 0    186.488285   216.225457   

      Customer_Satisfaction_Before  Customer_Satisfaction_After  \
1                       100.000000                   100.000000   
2                        98.780735                   100.000000   
3                        49.333766                    39.811841   
5                        58.075342                    69.404918   
6                        89.967827                    85.120975   
...                            ...                          ...   
9989                     70.249026                    76.630699   
9992                     81.851752                    83.163704   
9993                     72.235869                    91.898914   
9995                     88.438776                    98.418593   
9996                     92.261537                   100.000000   

      Purchase_Made  group  
1                 1      1  
2                 0      2  
3                 1      2  
5                 0      2  
6                 1      2  
...             ...    ...  
9989              0      2  
9992              1      0  
9993              0      0  
9995              2      1  
9996              2      2  

[5466 rows x 8 columns]

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['Group'] = le.fit_transform(df['Group'])
df['Customer_Segment'] = le.fit_transform(df['Customer_Segment'])
df['Purchase_Made'] = le.fit_transform(df['Purchase_Made'])


In [13]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
import numpy as np

# Standardize your data
scaler = StandardScaler()
standardized_features = scaler.fit_transform(df)

# Make one NaN (example)
true_value = standardized_features[0, 0]
standardized_features[0, 0] = np.nan

# Create imputer
mean_imputer = SimpleImputer(strategy='mean')

# Impute missing values
features_mean_imputed = mean_imputer.fit_transform(standardized_features)

print("True Value:", true_value)
print("Imputed Value:", features_mean_imputed[0, 0])

True Value: 0.40311826475992313
Imputed Value: -7.376363490579934e-05
